### PR TITLE
Change permutated to permuted

### PR DESCRIPTION
**Pull request by creativecreature**
## Overview
It should be permuted rather than permutated

### CODE REVIEW

**Comment by ccoVeille** [comment]
What happened to these changes?

Do you plan to include them in another PR?

**Comment by creativecreature** [comment]
> What happened to these changes?
> 
> Do you plan to include them in another PR?

@ccoVeille I’m not going to change the API but everything else was cherry picked to another PR which has been merged. I saw your comment about the lint settings and did that change. Thank you for pointing it out!

**Comment by ccoVeille** [comment]
Thanks, I was a bit disappointed that my review might be unseen

**Comment by ccoVeille** [comment]
The gosec was indeed updated with 

- https://github.com/creativecreature/sturdyc/pull/17

**Pull request closed without merging**
